//import type { Metadata } from "next";


import "./globals.css";
import {Poppins} from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  
});

/*export const metadata: Metadata = {
  title: "MICRO SAAS",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.className} bg-gray-100 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
